[2025-08-06T14:30:18.225-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-06T14:30:18.233-0400] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_tasks.dbt_debug manual__2025-08-06T18:30:08.253381+00:00 [queued]>
[2025-08-06T14:30:18.237-0400] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_tasks.dbt_debug manual__2025-08-06T18:30:08.253381+00:00 [queued]>
[2025-08-06T14:30:18.237-0400] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-08-06T14:30:18.249-0400] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_debug> on 2025-08-06 18:30:08.253381+00:00
[2025-08-06T14:30:18.252-0400] {standard_task_runner.py:72} INFO - Started process 26897 to run task
[2025-08-06T14:30:18.254-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_tasks.dbt_debug', 'manual__2025-08-06T18:30:08.253381+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmppt5jdknn']
[2025-08-06T14:30:18.255-0400] {standard_task_runner.py:105} INFO - Job 4: Subtask dbt_tasks.dbt_debug
[2025-08-06T14:30:18.288-0400] {task_command.py:467} INFO - Running <TaskInstance: dbt_dag.dbt_tasks.dbt_debug manual__2025-08-06T18:30:08.253381+00:00 [running]> on host LAPTOP-OO6HSLFU.localdomain
[2025-08-06T14:30:18.330-0400] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='huy' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T18:30:08.253381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T18:30:08.253381+00:00'
[2025-08-06T14:30:18.331-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-08-06T14:30:18.331-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-08-06T14:30:18.331-0400] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_debug state:running start_date:2025-08-06 18:30:18.234236+00:00
[2025-08-06T14:30:18.331-0400] {logging_mixin.py:190} INFO - Dag name:dbt_dag and current dag run status:running
[2025-08-06T14:30:18.331-0400] {taskinstance.py:740} INFO - ::endgroup::
[2025-08-06T14:30:18.332-0400] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-06T14:30:18.333-0400] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --project_dir /mnt/c/project/DBT/moviesDBT/dbt --profiles_dir /mnt/c/Users/huyng/.dbt']
[2025-08-06T14:30:18.339-0400] {subprocess.py:99} INFO - Output:
[2025-08-06T14:30:19.406-0400] {subprocess.py:106} INFO - Usage: dbt debug [OPTIONS]
[2025-08-06T14:30:19.406-0400] {subprocess.py:106} INFO - Try 'dbt debug -h' for help.
[2025-08-06T14:30:19.407-0400] {subprocess.py:106} INFO - 
[2025-08-06T14:30:19.407-0400] {subprocess.py:106} INFO - Error: No such option: --project_dir (Possible options: --profiles-dir, --project-dir)
[2025-08-06T14:30:19.619-0400] {subprocess.py:110} INFO - Command exited with return code 2
[2025-08-06T14:30:19.625-0400] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-06T14:30:19.630-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-08-06T14:30:19.630-0400] {logging_mixin.py:190} INFO - Task start:2025-08-06 18:30:18.234236+00:00 end:2025-08-06 18:30:19.629730+00:00 duration:1.395494
[2025-08-06T14:30:19.630-0400] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt_debug> dag:<DAG: dbt_dag> dagrun:<DagRun dbt_dag @ 2025-08-06 18:30:08.253381+00:00: manual__2025-08-06T18:30:08.253381+00:00, state:running, queued_at: 2025-08-06 18:30:08.266216+00:00. externally triggered: True>
[2025-08-06T14:30:19.630-0400] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-08-06T14:30:19.630-0400] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_tasks.dbt_debug, run_id=manual__2025-08-06T18:30:08.253381+00:00, execution_date=20250806T183008, start_date=20250806T183018, end_date=20250806T183019
[2025-08-06T14:30:19.652-0400] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-08-06T14:30:19.653-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task dbt_tasks.dbt_debug (Bash command failed. The command returned a non-zero exit code 2.; 26897)
Traceback (most recent call last):
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huynguyen2741/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-06T14:30:19.670-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-06T14:30:19.681-0400] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T14:30:19.682-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
